import enum

class TaskCategoryEnum(enum.Enum):
    MULTIFACTOR_RELEVANCY = 1
    STATEMENTS_LOGICAL_CONNECTION = 2
    COMMENT_ATTITUDE = 3
    SIZE_MATCHES = 4
    PRODUCT_QUALITY_ASSESSMENT = 5
    COMPOSITION_IDENTIFICATION = 6
    WEAR_DETERMINATION = 7
    PRODUCT_CONTENTS_CHECK = 8
    MULTIMODAL_MATCHING = 9
    CHECK_INFORMATION_SOURCE_RELIABILITY = 10
    TEXT_CONTRADICTIONS_CHECK = 11
    STATEMENT_INTENT_ANALYSIS = 12
    MANIPULATION_TECHNIQUES_DETECTION = 13
    GENRE_AND_STYLE_DEFINITION = 14
    PRODUCT_COUNTERFEIT_CHECK = 15
    MATERIAL_TYPE_DETERMINATION = 16
    PACKAGING_INTEGRITY_CHECK = 17
    PHOTO_AND_REAL_COLOR_COMPARISON = 18
    ITEM_INSTALLATION_CHECK = 19
